name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clone and build Weasis
      run: |
        mkdir temp
        cd temp
        git clone https://github.com/nroduit/Weasis.git
        cd Weasis
        git checkout 68e1f3a2f0b413ec1d6269314cd1456fd65b9950
        mvn clean install
    - name: Build google-healthcare-weasis-plugin
      run: |
        cd ../..
        mvn -clean install
